In [6]:
def fibonacci(n):
    my_list=[0,1]
    for i in range(0,n-2):
        my_list.append(my_list[i]+my_list[i+1])
    return my_list

fibonacci(10)

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34]

In [8]:
def sum2(n):
    n = n + 2
    return n

sum2(4)

6

In [10]:
# lambda expression example

sum2 = lambda n: n+2

sum2(4)

6

In [17]:
import numpy as np

my_list = [1,2,3]

my_first_array = np.array(my_list)

my_first_array

array([1, 2, 3])

In [21]:
my_list2 = [[1,2,3],[4,5,6],[7,8,9],[10,11,12]]

my_second_array = np.array(my_list2)

my_second_array

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [24]:
np.arange(0,5,2)

array([0, 2, 4])

In [32]:
np.zeros((3,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [36]:
np.ones((4,4))

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [38]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [42]:
np.linspace(5,50,5)

array([  5.  ,  16.25,  27.5 ,  38.75,  50.  ])

In [53]:
arr = np.random.rand(5)

arr

array([ 0.93371582,  0.82386466,  0.34771991,  0.59338646,  0.41190981])

In [57]:
np.random.randint(1000.20,5000.50,10)

array([4825, 1466, 4025, 2931, 1693, 2385, 2857, 1767, 2902, 1759])

In [60]:
my_second_array

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [62]:
my_second_array.shape

(4, 3)

In [65]:
my_second_array.dtype

dtype('int32')

In [67]:
my_third_array = np.array([1,2,3,4])

my_third_array

array([1, 2, 3, 4])

In [69]:
my_third_array.reshape(2,2)

array([[1, 2],
       [3, 4]])

In [71]:
my_third_array

array([1, 2, 3, 4])

In [73]:
my_third_array = my_third_array.reshape(2,2)

my_third_array

array([[1, 2],
       [3, 4]])

In [75]:
my_third_array.max()

4

In [77]:
my_third_array.min()

1

In [80]:
my_third_array.argmin()

0

In [81]:
my_third_array.min()

1

In [86]:
new_array = np.arange(0,26)

new_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25])

In [93]:
new_array[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25])

In [95]:
new_array[:] = 100

In [97]:
new_array

array([  0,   1,   2,   3,   4, 100, 100, 100, 100, 100,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25])

In [99]:
a = 5

c = a

c = c + 3

print(a,c)

5 8


In [102]:
arr1 = np.array([1,2,3,4,5])

arr2 = arr1[3:5]

arr2[:] = 100

print(arr1, arr2)

[  1   2   3 100 100] [100 100]


In [104]:
arr1 = np.array([1,2,3,4,5])

arr2 = arr1[3:5].copy()

arr2[:] = 100

print(arr1, arr2)

[1 2 3 4 5] [100 100]


In [106]:
my_second_array

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [112]:
my_second_array[3,2]

12

In [117]:
new_array = np.arange(0,26)

new_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25])

In [119]:
new_array > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True], dtype=bool)

In [121]:
bool_arr = new_array > 5

bool_arr

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True], dtype=bool)

In [125]:
new_array2 = new_array[new_array > 5]

new_array2

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
       23, 24, 25])

In [142]:
arr1

arr2 = np.array([0,2,3,4,5])

print(arr1,arr2)

[1 2 3 4 5] [0 2 3 4 5]


In [131]:
arr1 + 5

array([ 6,  7,  8,  9, 10])

In [144]:
arr1 / arr2

C:\Users\sathw\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([ inf,   1.,   1.,   1.,   1.])

In [146]:
arr3 = np.array(['a','b','c','d','e'])

print(arr3,arr3.dtype)

['a' 'b' 'c' 'd' 'e'] <U1


In [148]:
arr1 + arr3

TypeError: ufunc 'add' did not contain a loop with signature matching types dtype('<U11') dtype('<U11') dtype('<U11')

In [152]:
labels = ['Name','City','State']
data = ['Sathwik','Boston','MA']
d = {Name:['Sathwik','Kshitij'], City:['Boston','Dallas']}

In [155]:
import pandas as pd

my_series = pd.Series(data=data, index=labels)

In [157]:
my_series

Name     Sathwik
City      Boston
State         MA
dtype: object

In [159]:
my_series2 = pd.Series(data=[1,2,3,4],index=['A','B','C','D'])

In [161]:
my_series2

A    1
B    2
C    3
D    4
dtype: int64

In [163]:
my_series3 = pd.Series(data=[sum,max,len])

my_series3

0    <built-in function sum>
1    <built-in function max>
2    <built-in function len>
dtype: object

In [165]:
my_series['City']

'Boston'

In [168]:
my_dataframe = pd.DataFrame(np.random.randn(10,20))

In [173]:
type(my_dataframe[0])

pandas.core.series.Series

In [175]:
new_df = pd.read_csv("https://raw.githubusercontent.com/fivethirtyeight/data/master/college-majors/women-stem.csv")

new_df.head()

Rank  Major_code                                      Major Major_category  \
0     1        2419                      PETROLEUM ENGINEERING    Engineering   
1     2        2416             MINING AND MINERAL ENGINEERING    Engineering   
2     3        2415                  METALLURGICAL ENGINEERING    Engineering   
3     4        2417  NAVAL ARCHITECTURE AND MARINE ENGINEERING    Engineering   
4     5        2418                        NUCLEAR ENGINEERING    Engineering   

   Total   Men  Women  ShareWomen  Median  
0   2339  2057    282    0.120564  110000  
1    756   679     77    0.101852   75000  
2    856   725    131    0.153037   73000  
3   1258  1123    135    0.107313   70000  
4   2573  2200    373    0.144967   65000

In [182]:
new_df['Manual_total'] = new_df['Men']+new_df['Women']

new_df.head()

Rank  Major_code                                      Major Major_category  \
0     1        2419                      PETROLEUM ENGINEERING    Engineering   
1     2        2416             MINING AND MINERAL ENGINEERING    Engineering   
2     3        2415                  METALLURGICAL ENGINEERING    Engineering   
3     4        2417  NAVAL ARCHITECTURE AND MARINE ENGINEERING    Engineering   
4     5        2418                        NUCLEAR ENGINEERING    Engineering   

   Total   Men  Women  ShareWomen  Median  Manual_total  
0   2339  2057    282    0.120564  110000          2339  
1    756   679     77    0.101852   75000           756  
2    856   725    131    0.153037   73000           856  
3   1258  1123    135    0.107313   70000          1258  
4   2573  2200    373    0.144967   65000          2573

In [187]:
new_df['Men']

0       2057
1        679
2        725
3       1123
4       2200
5      21239
6        832
7      80320
8      12953
9      65511
10     33258
11      2949
12      8407
13      3526
14      6062
15     12453
16     45683
17      1835
18     99743
19      8181
20      2020
21      7398
22     41081
23      2695
24       488
25      2662
26     21773
27      3477
28       528
29      9005
       ...  
46     25463
47      1761
48      7426
49      8697
50     32923
51      6383
52      6607
53     18951
54       626
55      5291
56      5813
57       809
58      1589
59     10787
60      2744
61     11431
62     27015
63      8422
64      4944
65      4266
66      2563
67      4103
68      4747
69      5521
70    111762
71      3878
72     13487
73      7574
74      1225
75      3050
Name: Men, Length: 76, dtype: int64

In [ ]:
np.random.dirichlet